#!/usr/bin/env python3
"""Generate the Parameter Quick-Reference wiki page from src/canfix.json.

canfix.json is itself generated from the master spreadsheet (src/CAN-FIX.ods)
by src/canfix_json.py, so this script never touches the schema -- it only
reformats the already-generated parameter table into a Markdown quick reference
for the GitHub wiki.  Paths are resolved relative to the repo root, so it can be
run from anywhere:

    python tools/gen_param_reference.py
"""
import json
import os

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(REPO, "src", "canfix.json")
OUT = os.path.join(REPO, "wiki", "Parameter-Reference.md")
PAGES = "https://billmallard.github.io/canfix-spec"
JSON_URL = "https://github.com/billmallard/canfix-spec/blob/master/src/canfix.json"


def esc(text):
    """Escape a value for use inside a Markdown table cell."""
    return str(text).replace("|", "\\|").replace("\n", " ").strip()


def id_label(p):
    """A single ID, or a 'start-end' range when the parameter spans several."""
    count = p.get("count", 1) or 1
    start = p["id"]
    if count > 1:
        return f"{start}-{start + count - 1}"
    return str(start)


def range_label(p):
    lo = p.get("min")
    hi = p.get("max")
    has_lo = lo not in (None, "")
    has_hi = hi not in (None, "")
    if not has_lo and not has_hi:
        return ""
    return f"{lo if has_lo else ''} to {hi if has_hi else ''}"


def notes(p):
    bits = []
    idx = p.get("index")
    if idx:
        bits.append(f"Indexed by {idx}")
    fmt = p.get("format")
    if fmt:
        bits.append(fmt)
    for remark in (p.get("remarks") or []):
        bits.append(remark)
    return "; ".join(esc(b) for b in bits)


def main():
    with open(SRC, encoding="utf-8") as f:
        spec = json.load(f)

    groups = spec["groups"]
    params = spec["parameters"]
    version = spec.get("version", "")

    out = []
    out.append("# Parameter Quick-Reference")
    out.append("")
    out.append(
        f"Every CAN-FiX parameter (protocol version **{version}**), grouped by "
        f"CAN identifier range.  This page is generated from "
        f"[`src/canfix.json`]({JSON_URL}), which is built from the master "
        f"spreadsheet `src/CAN-FIX.ods` -- so it always matches the specification."
    )
    out.append("")
    out.append(
        f"For the full normative definitions (data encodings, frame formats, "
        f"meta data and bit fields) see the [complete specification]({PAGES}/), "
        f"in particular the [Parameters chapter]({PAGES}/parameters.html)."
    )
    out.append("")
    out.append("**Reading this table**")
    out.append("")
    out.append(
        "- **ID** -- the 11-bit CAN frame identifier. A range (e.g. `256-257`) "
        "means the parameter occupies several consecutive IDs for multiple "
        "instances."
    )
    out.append(
        f"- **Type** -- the [data type]({PAGES}/datatypes.html) of the value "
        "(see also [Data Types](Data-Types))."
    )
    out.append("- **Units / Range / Mult** -- engineering units, min/max, and the "
               "multiplier (the value each least-significant bit represents).")
    out.append(
        "- **Notes** -- the index dimension (for indexed parameters), the data "
        "format, and any per-parameter remarks."
    )
    out.append("")

    total_groups = 0
    for g in groups:
        gparams = sorted(
            (p for p in params if g["startid"] <= p["id"] <= g["endid"]),
            key=lambda x: x["id"],
        )
        if not gparams:
            continue
        total_groups += 1
        out.append(f"## {esc(g['name'])} ({g['startid']}-{g['endid']})")
        out.append("")
        out.append("| ID | Parameter | Type | Units | Range | Mult | Notes |")
        out.append("|---|---|---|---|---|---|---|")
        for p in gparams:
            row = [
                id_label(p),
                esc(p.get("name", "")),
                esc(p.get("type", "")),
                esc(p.get("units", "") or ""),
                esc(range_label(p)),
                esc(p.get("multiplier", "") or ""),
                notes(p),
            ]
            out.append("| " + " | ".join(row) + " |")
        out.append("")

    out.append("---")
    out.append("")
    out.append(
        f"_{len(params)} parameters across {total_groups} groups. Generated by "
        f"`tools/gen_param_reference.py` from `src/canfix.json` (version "
        f"{version}). Do not edit by hand -- edit the master spreadsheet and "
        f"regenerate._"
    )
    out.append("")

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(out))
    print(f"wrote {OUT}")
    print(f"  {len(params)} parameters, {total_groups} groups")


if __name__ == "__main__":
    main()
